### ISSUE TITLE
JSONStream or jsonstream?

### ISSUE THREAD

**Issue by refractalize** [substack/deps-sort#7]
take a look at this beautiful error message when I run `npm install browserify`:

    npm ERR! Darwin 14.3.0
    npm ERR! argv "node" "/usr/local/bin/npm" "i" "browserify"
    npm ERR! node v0.12.1
    npm ERR! npm  v2.7.4
    npm ERR! code ETARGET

    npm ERR! notarget No compatible version found: JSONStream@'>=1.0.3 <2.0.0'
    npm ERR! notarget Valid install targets:
    npm ERR! notarget ["0.0.0","0.1.0","0.1.1","0.1.2","0.1.3","0.2.0","0.2.1","0.2.2","0.2.3","0.3.0","0.3.1","0.3.2","0.3.3","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.5.0","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.7.0","0.7.1","0.8.0","0.7.2","0.7.3","0.7.4","0.8.1","0.8.2","0.8.3","0.8.4","0.9.0","0.10.0"]
    npm ERR! notarget 
    npm ERR! notarget This is most likely not a problem with npm itself.
    npm ERR! notarget In most cases you or one of your dependencies are requesting
    npm ERR! notarget a package version that doesn't exist.
    npm ERR! notarget 
    npm ERR! notarget It was specified as a dependency of 'deps-sort'
    npm ERR! notarget 

    npm ERR! Please include the following file with any support request:
    npm ERR!     /..../npm-debug.log

I get this running Mac OS X (which is case-insensitive).

I think NPM is confusing JSONSteam with jsonstream. Which, to be fair is a little confusing to myself :)

**Comment by refractalize** [comment]
Even `npm cache clear` doesn't help...

**Comment by refractalize** [comment]
Oh, I'm running `npm install browserify` (I've edited the original issue)

**Comment by deefour** [comment]
I'm having the same problem installing `cordova`. It's because of the dependency change from `JSONStream` to `jsonstream` in `package.json` 2 hours ago.

    "jsonstream": "^1.0.3",


275200e76f59cc2eab1fd77260349b983b771d82

**Comment by Ferdaszewski** [comment]
Same problem here when I run `npm install atomify` on Mac OS X.

`No compatible version found: JSONStream@'>=1.0.3 <2.0.0'`

**Comment by deefour** [comment]
I got my install working with the following up-front

```
npm install deps-sort@1.3.6
npm install insert-module-globals@6.4.0
npm install module-deps@3.7.10
```

These all have the same issue introduced with the JSONStream/jsonstream case conflict.

**Comment by callumacrae** [comment]
Two hours ago, our build broke:

```
311448 verbose unlock done using /Users/callumacrae/.npm/_locks/lmn-gulp-tasks-66ed9d312946097e.lock for /Users/callumacrae/Sites/lmn/eagle/node_modules/lmn-gulp-tasks
311449 verbose stack Error: No compatible version found: JSONStream@'>=1.0.3 <2.0.0'
311449 verbose stack Valid install targets:
311449 verbose stack ["0.0.0","0.1.0","0.1.1","0.1.2","0.1.3","0.2.0","0.2.1","0.2.2","0.2.3","0.3.0","0.3.1","0.3.2","0.3.3","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.5.0","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.7.0","0.7.1","0.8.0","0.7.2","0.7.3","0.7.4","0.8.1","0.8.2","0.8.3","0.8.4","0.9.0","0.10.0"]
311449 verbose stack
311449 verbose stack     at installTargetsError (/Users/callumacrae/.nvm/versions/node/v0.12.0/lib/node_modules/npm/lib/cache/add-named.js:259:12)
311449 verbose stack     at next (/Users/callumacrae/.nvm/versions/node/v0.12.0/lib/node_modules/npm/lib/cache/add-named.js:238:17)
311449 verbose stack     at setData (/Users/callumacrae/.nvm/versions/node/v0.12.0/lib/node_modules/npm/lib/cache/add-named.js:215:5)
311449 verbose stack     at RES (/Users/callumacrae/.nvm/versions/node/v0.12.0/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
311449 verbose stack     at f (/Users/callumacrae/.nvm/versions/node/v0.12.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
311449 verbose stack     at CachingRegistryClient.get_ (/Users/callumacrae/.nvm/versions/node/v0.12.0/lib/node_modules/npm/lib/cache/caching-client.js:125:16)
311449 verbose stack     at /Users/callumacrae/.nvm/versions/node/v0.12.0/lib/node_modules/npm/lib/cache/caching-client.js:91:14
311449 verbose stack     at evalmachine.<anonymous>:336:14
311449 verbose stack     at /Users/callumacrae/.nvm/versions/node/v0.12.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
311449 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
311450 verbose cwd /Users/callumacrae/Sites/lmn/eagle
311451 error Darwin 14.0.0
311452 error argv "/Users/callumacrae/.nvm/versions/node/v0.12.0/bin/node" "/Users/callumacrae/.nvm/versions/node/v0.12.0/bin/npm" "i"
311453 error node v0.12.0
311454 error npm  v2.5.1
311455 error code ETARGET
311456 error notarget No compatible version found: JSONStream@'>=1.0.3 <2.0.0'
311456 error notarget Valid install targets:
311456 error notarget ["0.0.0","0.1.0","0.1.1","0.1.2","0.1.3","0.2.0","0.2.1","0.2.2","0.2.3","0.3.0","0.3.1","0.3.2","0.3.3","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.5.0","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.7.0","0.7.1","0.8.0","0.7.2","0.7.3","0.7.4","0.8.1","0.8.2","0.8.3","0.8.4","0.9.0","0.10.0"]
311456 error notarget
311456 error notarget This is most likely not a problem with npm itself.
311456 error notarget In most cases you or one of your dependencies are requesting
311456 error notarget a package version that doesn't exist.
311457 verbose exit [ 1, true ]
311458 verbose unbuild node_modules/lmn.tarantula/node_modules/browserify/node_modules/deps-sort
311459 info preuninstall deps-sort@1.3.7
311460 info uninstall deps-sort@1.3.7
```

**Comment by lxe** [comment]
Yeah this broke things when installing "browserify@^9.0.8"

**Comment by mimiflynn** [comment]
I'm getting the same issue as Ixe but when installing `"grunt-browserify": "~3.2.0"`

**Comment by dspnorman** [comment]
Just ran into the same issue with my build:

`npm ERR! notarget No compatible version found: JSONStream@'>=1.0.3 <2.0.0'`

**Comment by substack** [comment]
This is an npm bug. It would be best if people raised these issues on npm, not here.

**Comment by abroz** [comment]
Not sure this is an npm bug. It's related to a code change from three hours ago.

**Comment by callumacrae** [comment]
Please work around it until the npm bug is fixed! It was a code change here that caused the error to be thrown.

**Comment by abroz** [comment]
https://github.com/substack/deps-sort/commit/275200e76f59cc2eab1fd77260349b983b771d82

**Comment by abroz** [comment]
Reverting this change fully resolves the issue.

**Comment by abrahamvelazquez** [comment]
https://twitter.com/chadhietala/status/596375511800000513

**Comment by abroz** [comment]
Understand the npm issue (https://github.com/substack/node-browserify/pull/1247), but this change shouldn't have happened until it was resolved.

**Comment by charlierudolph** [comment]
Please revert until npm resolves its issue

**Comment by abroz** [comment]
Resolved by https://github.com/substack/deps-sort/commit/2258e666f8ce0b25f4672cb5e3b5ddfef560d6a4

**Comment by zertosh** [comment]
This is all clear now!
